6 student education history model
tcet-opensource/erp-backend pull request #22
Opened 2023-04-10 18:29 UTC by Shivam-53

I  have created the schema for student education details, also i have used local mongodb

2023-04-11 16:57 UTC, Hitansh159 requested changes

2023-04-11 16:57 UTC, Hitansh159 commented on models/databaseUtil.js
> +// let DB_URL="mongodb://localhost:27017/new_data"
remove this comment

2023-04-11 16:57 UTC, Hitansh159 commented on routes/auth.js
> +
remove empty line

2023-04-11 16:57 UTC, Hitansh159 commented on models/std_edu_history.js
> +const { Schema, default: mongoose } = require('mongoose');
no need of this import

2023-04-11 16:58 UTC, Hitansh159 commented
Also mention which Issue this PR refers to

2023-04-12 05:47 UTC, Shivam-53 commented
Is everything good now?

2023-04-22 08:12 UTC, Hitansh159 approved these changes

2023-04-22 08:12 UTC, merged