250 Create all endpoints for organization
tcet-opensource/erp-backend pull request #311
Opened 2023-09-03 06:13 UTC by hricha11

## Description
Create all endpoints for organization
## Fixes
fixes #250 
## Checklist

- [x] Code follows project's style guidelines.
- [x] Changes are documented appropriately.

2023-09-03 09:32 UTC, sumitst05 requested changes
Changes requested.

2023-09-03 09:32 UTC, sumitst05 commented on controller/organization.js
> +    addNewOrganization, deleteOrganizationById, updateOrganizationById, getOrganization,
The function to get organization as defined in `services/organization.js` is named `getOrganizations` and not `getOrganization`

2023-09-03 09:32 UTC, sumitst05 commented on controller/organization.js
> +      const organization = await getOrganization(req.query);
change `getOrganization` to `getOrganizations` here as well

2023-09-03 10:01 UTC, sumitst05 commented on controller/organization.js
> +      await deleteOrganizationById(accredationId);
change `accreditationId` to `organizationId`

2023-09-03 15:10 UTC, kskarthik5 requested changes

2023-09-03 15:10 UTC, kskarthik5 commented on services/organization.js
> +};
add getOrganizations here

2023-09-09 14:55 UTC, TejasNair9977 approved these changes
LGTM

2023-09-09 15:10 UTC, TejasNair9977 approved these changes
LGTM

2023-09-09 15:10 UTC, merged