[Added] Curd Operation in Semester Model
tcet-opensource/erp-backend pull request #324
Opened 2023-09-06 11:29 UTC by deepti-50

Issue no . #282 
[ADDED]
Semester Curd operation in semester.js file in model folder

2023-09-06 12:24 UTC, TejasNair9977 requested changes
some changes

2023-09-06 12:24 UTC, TejasNair9977 commented on models/semester.js
> +  number:{Number,enum: [1,2,3,4,5,6,7,8], required:true},
it should be type: Number

2023-09-08 14:48 UTC, Aastha-S-Rai approved these changes
LGTM !!

2023-09-08 19:00 UTC, TejasNair9977 approved these changes

2023-09-08 19:00 UTC, merged