Created module model
tcet-opensource/erp-backend pull request #66
Opened 2023-06-13 12:51 UTC by Dhruvrg

fixes #38

2023-06-14 04:05 UTC, TejasNair9977 requested changes
Please make the above changes.

2023-06-14 04:05 UTC, TejasNair9977 commented on models/module.js
> +export default modules;
Very small change, could you please make modules singular? Simply rename it to moduleModel. We need it in PascalCase for models.
```suggestion
const moduleModel= new connector.model('Module', moduleSchema);
export default moduleModel;
```

2023-06-16 07:47 UTC, Hitansh159 requested changes

2023-06-16 07:47 UTC, Hitansh159 commented on models/module.js
> +  modNo: { type: Number, required: true },
change this to moduleNo

2023-06-16 12:10 UTC, Hitansh159 approved these changes

2023-06-16 18:54 UTC, merged