Performed Crud on AccreditationModel
tcet-opensource/erp-backend pull request #79
Opened 2023-06-14 05:15 UTC by VinitChawda06

fixes #49

2023-06-14 05:25 UTC, TejasNair9977 requested changes
Just a few changes.

2023-06-14 05:25 UTC, TejasNair9977 commented on models/accreditation.js
> +const Accreditation = new connector.model('Accreditation', accreditationSchema);
please rename this back to AccreditationModel

2023-06-14 05:25 UTC, TejasNair9977 commented on models/accreditation.js
> +    const res = await Accreditation.findOneAndDelete(filter);
make this change in every line under it too

2023-06-16 10:15 UTC, Hitansh159 requested changes

2023-06-16 10:15 UTC, Hitansh159 commented on models/accreditation.js
> +import { logger } from "#util";
remove logger

2023-06-16 10:15 UTC, Hitansh159 commented on models/accreditation.js
> +connector.set("debug", true);
remove debug as well

2023-06-16 19:08 UTC, Hitansh159 approved these changes

2023-06-16 19:08 UTC, merged