event model
tcet-opensource/erp-backend pull request #84
Opened 2023-06-14 10:14 UTC by Parikshit-007

#57

2023-06-14 10:24 UTC, kskarthik5 commented
please add the attendance attribute in the schema

2023-06-14 10:29 UTC, kskarthik5 requested changes

2023-06-14 10:29 UTC, kskarthik5 commented on models/event.js
> +    infra: { type: String, required: true },
infra will be of type:Infrastructure and add attendance attribute which be be of type:[Attendance]

2023-06-14 10:29 UTC, kskarthik5 commented on models/event.js
> +    infra: { type: String, required: true },
put the necessary imports as well

2023-06-27 16:20 UTC, Hitansh159 commented
With the new Plan, this model would be redesigned so closing this PR.

2023-06-27 16:20 UTC, closed without merging