Added PR Template
tcet-opensource/erp-backend pull request #94
Opened 2023-06-19 08:22 UTC by VinitChawda06

2023-06-20 19:24 UTC, Hitansh159 requested changes

2023-06-20 19:24 UTC, Hitansh159 commented on ,github/pull_request_template.md
rename folder to `.github`

2023-06-21 05:21 UTC, VinitChawda06 commented on ,github/pull_request_template.md
Done

2023-06-22 18:33 UTC, Hitansh159 approved these changes

2023-06-22 18:34 UTC, merged